name: Pack Nuget

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      # .NET
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build .\src\DotMarkCMS\DotMarkCMS.csproj --configuration Release /p:Version=${VERSION}

      - name: Pack .NET Project
        run: dotnet pack .\src\DotMarkCMS\DotMarkCMS.csproj --configuration Release /p:Version=${VERSION}

      - name: Upload Nuget Package
        run: dotnet nuget push .\src\DotMarkCMS\bin\Release\DotMarkCMS.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
